### ISSUE TITLE
It's not Python

### ISSUE THREAD

**Issue by lmazuel** [Azure/swagger-to-sdk-ts#10]
Seems to me the most important issue right? :)

More seriously, I would be interested in the why you think it's better to re-implement it in TS, instead of maintaining it in Python. As a feedback to me, and some kind of closure :)

**Comment by daschult** [comment]
Sorry, I just saw this issue.
There are a couple of reasons we wanted to rewrite it. Changing from Python to TypeScript is a big one simply because of the expertise we have in the team with TypeScript. So few of our team members are competent in Python and that really discourages us from wanting and being able to contribute to the product. Changing to TypeScript means that almost everyone on the team will be able to ramp up quickly and contribute to this product if they needed to.
The other issue comes around code reuse. We'd like to share logic between this service and the OpenAPI-Hub. The OpenAPI-Hub is written in TypeScript, and so it makes sense to rewrite Swagger To SDK in TypeScript rather than rewriting the Hub in Python (especially with my first point in mind).
I hope that makes sense.
